### ISSUE TITLE
Tag OpenSSL_1_1_1u-quic1 points to wrong commit

### ISSUE THREAD

**Issue by siloportem** [quictls/openssl#123]
The tag [OpenSSL_1_1_1u-quic1](https://github.com/quictls/openssl/releases/tag/OpenSSL_1_1_1u-quic1) points to commit [70c2912](https://github.com/quictls/openssl/commit/70c2912f635aac8ab28629a2b5ea0c09740d2bda), like tag [OpenSSL_1_1_1u](https://github.com/quictls/openssl/releases/tag/OpenSSL_1_1_1u), when it should point to commit [636c615](https://github.com/quictls/openssl/commit/636c615c139061b125a25461708f4afc79284f83).

**Comment by wbl** [comment]
Woops! I forgot to git pull after the merge.

**Comment by wbl** [comment]
I have now forceibly fixed the problem. You will need to delete tags locally and repull them to catch up. I think the release always was right.
