### ISSUE TITLE
3.1.3 question

### ISSUE THREAD

**Issue by elyograg** [quictls/openssl#142]
Please note that this is NOT a demand for a new version or a complaint about this project's efforts.  It is only a discussion.

Some time ago, I saw the 3.1.3 announce on the openssl mailing list.  Usually this project publishes an update within a few days of announcement by the openssl project.  I didn't see one here, and basically forgot about it until now.

Then I saw the 3.2 alpha announcement, and thought for sure a 3.1.3 release of quictls would have happened by now, but it's still not here.

So I went looking at the openssl changelog ... and found that 3.1.3 mentioned one change ... which appears to only apply to Windows.

Maybe the Windows issue is not something this project really cares about.  Which is a little odd given that the main README says quictls is an effort driven by Akamai and Microsoft.  Can someone shed some light on this?  I'm thinking because I use quictls on Linux that 3.1.3 would not offer me any benefit compared to 3.1.2.

**Comment by tmshort** [comment]
Hi, my paying job no longer directly involves OpenSSL... So, I've been a bit lax here. I just pushed 3.0.11+quic. I will be rebasing onto 3.1.3 today and pushing a PR, likely today.

**Comment by elyograg** [comment]
> Hi, my paying job no longer directly involves OpenSSL... So, I've been a bit lax here. I just pushed 3.0.11+quic. I will be rebasing onto 3.1.3 today and pushing a PR, likely today.

Thanks for the info!  I think you should take as much time as you need.
