### ISSUE TITLE
Plans for update to 3.0.11 or other recent openssl releases?

### ISSUE THREAD

**Issue by baparham** [quictls/openssl#146]
What is the plan for releasing some of the newer OpenSSL releases, such as 3.0.11?

They have done some security releases and it would be good to stay up to date with these.

https://github.com/openssl/openssl/releases

Would you like me to try and put together a PR with such an upgrade or something?

**Comment by baparham** [comment]
related existing discussion: https://github.com/quictls/openssl/discussions/139

**Comment by eilandert** [comment]
I'd like to know too ;-)  Bookworm is overriding 3.0.10+quic now with their 3.0.11 release

**Comment by baparham** [comment]
@tmshort we can see you already fixed it last week (https://github.com/quictls/openssl/pull/143), so is there anything blocking a tag/release?

**Comment by baparham** [comment]
cc @richsalz @wbl 🙏

**Comment by richsalz** [comment]
The only thing "blocking a tag" is that it is one extra step that nobody remembers to do.

**Comment by richsalz** [comment]
You should look for a branch name, which *has* to happen, as an indication, rather than a tag.

**Comment by tmshort** [comment]
Tags have been created.
