### ISSUE TITLE
What now?

### ISSUE THREAD

**Issue by Zoey2936** [quictls/openssl#174]
The latest release mentions https://github.com/quictls/quictls, but there are no release. The latest release here is based on v3.3.0 which seems to contain CVEs. So what should I use now? Currently, I'm using v3.1.x+quic, so what would you recommend?

**Comment by wbl** [comment]
We have rebased onto 3.1.7 which fixes the CVEs, and will continue to rebase on that 3.1.x line. I would recommend sticking to that.

The 3.3.0 branch will see further development at quictls and we will independently fix CVEs rather than continue to rebase.

**Comment by Zoey2936** [comment]
Thanks!
