### ISSUE TITLE
SSL_CTX_set_quic_method manpage removed

### ISSUE THREAD

**Issue by Sp1l** [quictls/openssl#22]
Between 9398922 and 32be828, the `man/man3/SSL_CTX_set_quic_method.3.gz` manpage went missing from make install.
Browsed a bit through the commits but couldn't find out how this was in alpha12 but is no longer in alpha13

**Comment by tmshort** [comment]
Upstream alpha12 to alpha13 included changes in how documentation files are built. PR #20 fixes this, but hasn't had any traction.

**Comment by tmshort** [comment]
Resolved with #20
