### ISSUE TITLE
About change in openssl/openssl

### ISSUE THREAD

**Issue by luyahan** [quictls/openssl#40]
I add riscv target to openssl/openssl_1_1_1: https://github.com/openssl/openssl/pull/14724
I want to add openssl-riscv into nodejs
So  how to add this [patch](https://github.com/openssl/openssl/pull/1472) into quictls/openssl ?

**Comment by kaduk** [comment]
Typically we would just wait and obtain the change as part of the next release, in this case OpenSSL 1.1.1l.

**Comment by luyahan** [comment]
> Typically we would just wait and obtain the change as part of the next release, in this case OpenSSL 1.1.1l.

Thanks!
