### ISSUE TITLE
SSL_clear do not reset the state of the QUIC members

### ISSUE THREAD

**Issue by jpboivin** [quictls/openssl#55]
Hello,

It looks like `SSL_clear` doesn't reset any QUIC-specific members (like the `quic_read_level` / `quic_write_level`). This means that it is currently impossible to re-use the same `SSL` object to re-establish another connection.

I guess we should reset the following members:
- `quic_read_level` to `ssl_encryption_inititial`
- `quic_write_level` to `ssl_encryption_inititial`
- `quic_latest_level_received` to `ssl_encryption_inititial`
- `quic_buf` to an empty buffer
- `quic_input_data_head` to `NULL`
- `quic_input_data_tail` to `NULL`
- `quic_next_record_start` to `0`

Am I missing anything?

**Comment by tmshort** [comment]
I'm working on this, but it's non-trivial, as `SSL_clear()` is called in unexpected places...

**Comment by tatsuhiro-t** [comment]
I found this issue with 3.0.0, but I can pin dependency down to the working revision, so either is fine.

**Comment by jpboivin** [comment]
> For those who are experiencing problems, is it on 1.1.1 or 3.0? (i.e. which one should should I try an initial patch for?)

We are using 1.1.1, but if your solution works fine for @tatsuhiro-t, it should work fine for us too. We are using ngtcp2, but with a custom crypto layer, also based on OpenSSL.

**Comment by tmshort** [comment]
I pushed a new fix for 1.1.1 (#61) and 3.0 (#62). Could someone (@tatsuhiro-t ?) see if it works better for them?

**Comment by nibanks** [comment]
@tmshort I can't right now, but if you ever want to run a 1.1.1 change through the (quite extensive) [MsQuic](https://github.com/microsoft/msquic) automated CI, simply make a draft PR to MsQuic with an updated submodule and I'll approve the CI run. It should give you coverage on Linux, Windows, and macOS; functional, stress and performance. We can let it run to get the results and then close the PR afterwards.

**Comment by tmshort** [comment]
Thanks @nibanks: https://github.com/microsoft/msquic/pull/2104

**Comment by jpboivin** [comment]
@tmshort Tested your changes with 1.1.1 and I could remove the `SSL_do_handshake` that we had to add. The clear also does work as expected.

**Comment by tatsuhiro-t** [comment]
The fix works for me.  Thank you!
