### ISSUE TITLE
Where is QUIC version?

### ISSUE THREAD

**Issue by artenaki** [quictls/openssl#66]
Contents of https://github.com/quictls/openssl/archive/refs/tags/openssl-3.0.0.tar.gz are completely identical to https://www.openssl.org/source/openssl-3.0.0.tar.gz
Are you fooling us?

**Comment by tmshort** [comment]
We haven't been tagging releases, so if you get the `openssl-3.0.0` tag, it will be identical to upstream.
Please use the release branches, which are based on upstream tag names `+quic`. So you would be interested in `openssl-3.0.0+quic`: https://github.com/quictls/openssl/commits/openssl-3.0.0%2Bquic
Access via `git`

**Comment by tmshort** [comment]
_IF_ we had created a release tag, it would be in the form of `openssl-3.0.0+quic-release1` per the https://github.com/quictls/openssl/blob/openssl-3.0.0%2Bquic/README.md

**Comment by artenaki** [comment]
Thanks.
I used these commands:
```
https://github.com/quictls/openssl/commits/openssl-3.0.0+quic

git clone https://github.com/quictls/openssl
cd openssl
git submodule update --init --recursive
git checkout 0ce9b022cb421b564bed9ebc9469e96258ec175d
```

Although, there's also this one:
`git clone --depth 1 -b openssl-3.0.0+quic https://github.com/quictls/openssl`

as shown [here](https://github.com/ngtcp2/ngtcp2).
I think you need to change the description and be more explicit about how to get QUIC version.
