### ISSUE TITLE
EVP_AEAD_CTX can not be found

### ISSUE THREAD

**Issue by wangfuyu** [quictls/openssl#72]
I am trying to compile quic library with openssl-3.0.1+quic, but maker show lots error info, like:
1) error: unknown type name ‘EVP_AEAD_CTX’
2) openssl/aead.h: No such file or directory
3) implicit declaration of function ‘EVP_aead_aes_128_gcm’

These structures/apis about AEAD were used by quiche, could you tell me how can I compile quiche or lsquic with openssl-3.0.1+quic but not with boringssl? Thanks~

![image](https://user-images.githubusercontent.com/12257285/149498375-efd2c882-7588-4244-9d35-dde1eecb13d1.png)

**Comment by tmshort** [comment]
`EVP_AEAD_CTX` (and `EVP_AEAD`) is a BoringSSL construct that does not exist in OpenSSL.
I suspect those using Chromium QUIC are compiling an older version, but I can't be sure. (I believe the team that this was originally written for is using an older version.)
It would be good to hear from those using QUICTLS with Chromium QUIC how they are compiling.

**Comment by tmshort** [comment]
I'm also noting that recent quiche is using the `bssl` namespace, which this doesn't provide. BoringSSL includes C++ code (hence the `bssl` namespace), but OpenSSL (and subsequently QuicTLS) is written in C.

**Comment by richsalz** [comment]
This project is about adding the de-facto QUIC API's to OpenSSL.  Not implementing all of boringSSL API's.  Closing this.
