### ISSUE TITLE
Difference between x86_64 and aarch64 -- lib64 vs. lib

### ISSUE THREAD

**Issue by elyograg** [quictls/openssl#83]
I don't know if this is a bug or not, so I am starting with the question issue type.

I am building and installing the 3.0.x version of this openssl to use with the development version of haproxy.  I install it into /opt/qucitls.

On x86_64, the library files go into a "lib64" subdirectory.  But on aarch64, also a 64-bit architecture, the library files go into a "lib" subdirectory.

This discrepancy means that my build script for haproxy must detect whether or not /opt/quictls/lib64 exists and adjust the build to the correct directory -- the script I had working on x86_64 systems did not work as-is on my raspberry pi.

Is the behavior I am seeing correct?

**Comment by tmshort** [comment]
I believe this is the same way the upstream openssl project does it. Because there is no "32-bit" version for "aarch64" everything just gets put into "lib". This should be identical to vanilla openssl. Please try that and see if it is the same.
