### ISSUE TITLE
About change in openssl/openssl

### ISSUE THREAD

**Issue by shipujin** [quictls/openssl#95]
I add LoongArch target to openssl/openssl [3.0]: [openssl#18807](https://github.com/openssl/openssl/pull/18807)
I want to add openssl-loongarch64 into nodejs
So how to add this patch into quictls/openssl ?

Cheers~

**Comment by tmshort** [comment]
If it was put into the `openssl-3.0` branch, then when `openssl-3.0r` is tagged, it will be pulled in.
We only pull from upstream on tags.

**Comment by shipujin** [comment]
OK, thanks~
