### ISSUE TITLE
Please  keeping current with OpenSSL (v3.0.6)

### ISSUE THREAD

**Issue by cheungxi** [quictls/openssl#99]

**Comment by tmshort** [comment]
3.0.6 was withdrawn by upstream openssl; so although there's a version, we don't recommend using it.
When 3.0.7 is released, quictls will also be released.

**Comment by cheungxi** [comment]
> 

Thank you

**Comment by cheungxi** [comment]
> 3.0.6 was withdrawn by upstream openssl; so although there's a version, we don't recommend using it. When 3.0.7 is released, quictls will also be released.

Thank you.
